### ISSUE TITLE
New Twitch video urls

### ISSUE THREAD

**Issue by MarkSoupial** [DumpsterDoofus/ReChatDownloader#1]
The program doesn't seem to be able to use the new format of Twitch VOD urls.
Also, if a video has no chat the program errors without writing any srt files.  So, if using the 'pastbroadcasts' function it just bloats the log for nothing.

![untitled](https://user-images.githubusercontent.com/32455387/31077767-c502dcbe-a74d-11e7-97df-c2047bdee708.png)

**Comment by DumpsterDoofus** [comment]
@MarkSoupial Sorry for the 2 year delay! The app has recently been rewritten. 

The first bug (application choking on new format of Twitch VOD URLs) is no longer an issue, since single-video downloads now just take the video ID. 

The second bug has also been fixed. If there are no comments for a video, instead of failing the run, it just logs a warning that no comments were found. I tested by running `dotnet TwitchChatDownloader.dll --username murphagator` to download all videos from the user you provided in your screenshot, and it ran without a hitch. An an empty SRT file is still saved, just for consistency:

![image](https://user-images.githubusercontent.com/6626631/53702133-7f44c180-3db8-11e9-99b9-530ba2e0e374.png)

Going to close this as fixed, unless you have any objections.
